# Cargo.toml -- Aldaron's Codec Interface / PNG
# Copyright (c) 2017-2018  Jeron A. Lau <jeron.lau@plopgrizzly.com>
# Licensed under the MIT LICENSE
#                             _        _
#                            /@\——————/@\
# .———  .                   |   o    o   |     .————      .            .
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   .
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   |
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |
#                 |        \              /                              __/
#                           ¯————————————¯

[package]
name = "aci_png"
version = "0.6.1"
authors = [
	"Jeron A. Lau <jeron.lau@plopgrizzly.com>"
]

license = "MIT"
documentation = "https://docs.rs/aci_png"
homepage = "http://plopgrizzly.com/aci_png"
repository = "https://github.com/plopgrizzly/aci_png"

readme = "README.md"
description = "Encode and decode png and apng(TODO) image files."
keywords = ["image", "png", "codec", "parse", "decoder"]
categories = ["encoding", "parsing", "data-structures", "multimedia"]

exclude = [
	"examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore",
	"_config.yml", "ISSUE_TEMPLATE.md", "icon.ico", "icon.png"
]

[dependencies]
afi = "^0.5"
flate2 = "^0.2"
byteorder = "1.2.2"
