# Aldaron's Codec Interface - PNG                                              #
# Copyright (c) 2017 Plop Grizzly, Jeron Lau <jeron.lau@plopgrizzly.com>       #
# Licensed under the MIT LICENSE                                               #
#                             _        _                                       #
#                            /@\——————/@\                                      #
# .———  .                   |   o    o   |     .————      .            .       #
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   . #
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   | #
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /  #
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |   #
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |   #
#                 |        \              /                              __/   #
#                           ¯————————————¯                                     #
# Cargo.toml                                                                   #

[package]
name = "aci_png"
version = "0.2.0"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.tech>"]
description = """
Aldaron's Codec Interface - PNG: A library for decoding png image files.
"""
keywords = [ "Image", "PNG", "Codec", "Parse" ]
categories = [
	"data-structures", "encoding", "parser-implementations", "parsing"
]
license = "MIT"
documentation = "https://docs.rs/aci_png"
homepage = "http://plopgrizzly.com/aci_png"
repository = "https://github.com/plopgrizzly/aci_png"
readme = "README.md"
exclude = [ "examples/*", ".gitignore", "TODO" ]

[dependencies]
png = "^0.9"
